version: "3.3"
services:
  app:
    container_name: projects_gqlserver_dev
    image: bsapaka/projects_gqlserver_dev
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - $PORT:$PORT
    environment:
      PORT: $PORT
      PROJECTS_JSONAPI_ENDPOINT_URL: $PROJECTS_JSONAPI_ENDPOINT_URL
    volumes:
      - "../../:/var/app"
